project:
  type: website
  output-dir: docs

website:
  title: "Science School of Quantitative Ecology"
  
  page-footer:
    right: "This page is built by OndÅ™ej Mottl with â¤ï¸ and [Quarto](https://quarto.org/)."
  
  site-url: https://ssoqe.github.io/SSoQE_website/
  repo-url: https://github.com/SSoQE/SSoQE_website
  repo-actions: source
  
  image: photos/logo_v2.png
  favicon: photos/logo_v2.png
  back-to-top-navigation: true
  
  navbar:
    title: SSoQE
    search: true
    left:
      - text: "About the Workshop 2025ğŸ“"
        menu:
          - text: General InformationğŸ“„
            href: About/general_info.qmd
          - text: ProgramğŸ“…
            href: About/program.qmd
          - text: LogisticsğŸ•ï¸
            href: About/logistics_cz.qmd
          - text: RegistrationğŸ“
            href: About/registration.qmd
          - text: Pre-workshop technical SetupğŸ–¥ï¸
            href: About/pre_workshop.qmd
      - text: Meet the TeamğŸ‘¥
        href: team.qmd
      - text: "Previous runsğŸƒâ€â™‚ï¸"
        menu:
        - text: "2024"
          href: Previous/2024/2024.qmd
    tools:
      - icon: github
        href: https://github.com/SSoQE/SSoQE_website

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 2

