project:
  type: website
  output-dir: docs

website:
  title: "Science School of Quantitative Ecology"
  navbar:
    left:
      - href: about.qmd
        text: About the WorkshopğŸ“
      - href: team.qmd
        text: Meet the TeamğŸ‘¥
      - href: logistics.qmd
        text: LogisticsğŸ•ï¸
      - href: registration.qmd
        text: RegistrationğŸ“
    tools:
      - icon: github
        href: https://github.com/OndrejMottl/SSoQE_website

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 2

editor: visual

